[book]
language = "en"
multilingual = false
src = "src"
title = "Rust for C#/.NET Developers"

[output.html]
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/microsoft/rust-for-dotnet-devs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/microsoft/rust-for-dotnet-devs/edit/main/{path}"

[output.html.playground]
runnable = false
